[package]
name = "jsc"
version = "0.1.0"
authors = ["Phil Eaton <philneaton95@gmail.com>"]

[dependencies]
clap = "~2.27.0"
esprit = "~0.0.5"
easter = "~0.0.5"
joker = "~0.0.5"
serde = "~1.0"
serde_json = "~1.0"
serde_derive = "~1.0"