version: 2
jobs:
  build:
    docker:
      - image: node:11-slim
    steps:
      - checkout
      - run:
          name: Install debian-packaged dependencies
          command: |
            apt update
            # curl/apt-transport-https for yarn, python, build-essential for node-gyp
            apt install -y curl apt-transport-https python build-essential
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
            apt update && apt install -y yarn
      - run:
          name: Install Node dependencies, run tests
          command: |
            yarn
            yarn test